#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v10
# autospec commit: 5905be9
#
Name     : qt6serialport
Version  : 6.7.1
Release  : 14
URL      : https://download.qt.io/official_releases/qt/6.7/6.7.1/submodules/qtserialport-everywhere-src-6.7.1.zip
Source0  : https://download.qt.io/official_releases/qt/6.7/6.7.1/submodules/qtserialport-everywhere-src-6.7.1.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qt6serialport-lib = %{version}-%{release}
Requires: qt6serialport-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(libudev)
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the qt6serialport package.
Group: Development
Requires: qt6serialport-lib = %{version}-%{release}
Provides: qt6serialport-devel = %{version}-%{release}
Requires: qt6serialport = %{version}-%{release}

%description dev
dev components for the qt6serialport package.


%package lib
Summary: lib components for the qt6serialport package.
Group: Libraries
Requires: qt6serialport-license = %{version}-%{release}

%description lib
lib components for the qt6serialport package.


%package license
Summary: license components for the qt6serialport package.
Group: Default

%description license
license components for the qt6serialport package.


%prep
%setup -q -n qtserialport-everywhere-src-6.7.1
cd %{_builddir}/qtserialport-everywhere-src-6.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716951008
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1716951008
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6serialport
cp %{_builddir}/qtserialport-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6serialport/79453f55fa8ee32d7b95581473edcbfd043e088f || :
cp %{_builddir}/qtserialport-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6serialport/dc8f2e570bf431427dbc3bab9d4d551b53a60208 || :
cp %{_builddir}/qtserialport-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6serialport/7713a1753ce88f2c7e6b054ecc8e4c786df76300 || :
cp %{_builddir}/qtserialport-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6serialport/c70af14df11e3908dfc10397b1ba4b1f346661f3 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/QtSerialPort/6.7.1/QtSerialPort/private/qserialport_p.h
/usr/include/QtSerialPort/6.7.1/QtSerialPort/private/qserialportinfo_p.h
/usr/include/QtSerialPort/6.7.1/QtSerialPort/private/qtserialport-config_p.h
/usr/include/QtSerialPort/QSerialPort
/usr/include/QtSerialPort/QSerialPortInfo
/usr/include/QtSerialPort/QtSerialPort
/usr/include/QtSerialPort/QtSerialPortDepends
/usr/include/QtSerialPort/QtSerialPortVersion
/usr/include/QtSerialPort/qserialport.h
/usr/include/QtSerialPort/qserialportglobal.h
/usr/include/QtSerialPort/qserialportinfo.h
/usr/include/QtSerialPort/qtserialport-config.h
/usr/include/QtSerialPort/qtserialportexports.h
/usr/include/QtSerialPort/qtserialportversion.h
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtSerialPortTestsConfig.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortConfig.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortConfigVersion.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortDependencies.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortTargets.cmake
/usr/lib64/cmake/Qt6SerialPort/Qt6SerialPortVersionlessTargets.cmake
/usr/lib64/libQt6SerialPort.prl
/usr/lib64/libQt6SerialPort.so
/usr/lib64/pkgconfig/Qt6SerialPort.pc
/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport_private.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libQt6SerialPort.so.6.7.1
/usr/lib64/libQt6SerialPort.so.6
/usr/lib64/libQt6SerialPort.so.6.7.1
/usr/lib64/qt6/metatypes/qt6serialport_relwithdebinfo_metatypes.json
/usr/lib64/qt6/modules/SerialPort.json

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6serialport/7713a1753ce88f2c7e6b054ecc8e4c786df76300
/usr/share/package-licenses/qt6serialport/79453f55fa8ee32d7b95581473edcbfd043e088f
/usr/share/package-licenses/qt6serialport/c70af14df11e3908dfc10397b1ba4b1f346661f3
/usr/share/package-licenses/qt6serialport/dc8f2e570bf431427dbc3bab9d4d551b53a60208
